version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "US/Pacific"
    groups:
      updates:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
    assignees:
      - "grayespinoza"
    commit-message:
      prefix: "chore"
